
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"U_kgDOB3b6TA","is_bot":false,"login":"Hungkhuu04","name":""},"headRefName":"hk-form-component-recreq","number":89,"title":"hk - recommendation request form components with testing","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/89"},{"author":{"id":"U_kgDOB3b6TA","is_bot":false,"login":"Hungkhuu04","name":""},"headRefName":"hk-recreq-fixtures","number":87,"title":"Hk recreq fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/87"}]
