
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-HelpRequest-copy-backend","number":65,"title":"mw - Copied files for Articles from team01 to team 02","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/65"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-fixtures","number":64,"title":"jj - added ucsbDiningCommonsMenuItemFixtures.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/64"}]
