
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-index","number":105,"title":"yz-Index Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/105"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-create","number":104,"title":"yz-Create Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/104"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-placeholders","number":103,"title":"yz-Copy Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/103"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-tablecomponent","number":102,"title":"yz-Table Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/102"},{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-helprequests-edit-page","number":101,"title":"mw - Add Edit page for Help Requests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/101"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-formcomponent","number":100,"title":"yz - Form Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/100"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"Simon-MenuItemReviews-Placeholders","number":92,"title":"Simon menu item reviews create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/92"}]
