
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-table-component","number":68,"title":"jj - ucsb dining commons menu item table component","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/68"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-form-component","number":67,"title":"jj - ucsb dining commons menu item form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/67"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-fixtures","number":66,"title":"aw - Adds fixtures for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/66"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-fixtures","number":64,"title":"jj - added ucsbDiningCommonsMenuItemFixtures.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/64"}]
