
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-helprequests-integration-tests","number":123,"title":"mw - Add integration tests for Help Requests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/123"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-menuitems-e2e-tests","number":122,"title":"jj - ucsbdiningcommonsmenuitems e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/122"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-menuitems-integration-tests","number":121,"title":"jj - ucsbdiningcommonsmenuitems integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/121"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-organizations-edit","number":107,"title":"yz-Edit Page for UCSBOrganization","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/107"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"Simon-MenuItemReviews-Placeholders","number":92,"title":"Simon menu item reviews create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/92"}]
