
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles","number":62,"title":"aw - Copied files for Articles from team01 to team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/62"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-copy-backend","number":61,"title":"jj - copied backend CRUD operations","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/61"}]
