
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-create-page","number":80,"title":"Aw articles create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/80"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-placeholder-pages","number":79,"title":"Aw articles placeholder pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/79"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-table","number":78,"title":"Aw articles table","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/78"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-UCSBOrganization-copybackend","number":76,"title":"yz-Copy files for Backend CRUD API UCSBOrganization from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/76"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-edit-page","number":74,"title":"jj - ucsb dining commons menu item edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/74"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-index-page","number":71,"title":"jj - ucsb dining commons menu item index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/71"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-create-page","number":70,"title":"jj - ucsb dining commons menu item create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/70"}]
