
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-12
owner: ucsb-cs156-s25
repo_name: team02-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-edit-page","number":85,"title":"Aw articles edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/85"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-index-page","number":84,"title":"Aw articles index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/84"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"Simon-MenuItemReviews-Placeholders","number":83,"title":"Simon menu item reviews placeholders","url":"https://github.com/ucsb-cs156-s25/team02-s25-12/pull/83"}]
